# Generated by Django 5.1.1 on 2024-09-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leetcodeproblemsmodel',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], max_length=15, null=True),
        ),
    ]
