# Generated by Django 5.1.1 on 2024-09-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc_api', '0002_leetcodeproblemsmodel_difficulty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contest',
            new_name='ContestModel',
        ),
    ]
