# Generated by Django 5.1.1 on 2024-09-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_api', '0003_rename_contest_contestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcodeproblemsmodel',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=15, null=True),
        ),
    ]
