# Generated by Django 5.1.1 on 2024-09-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_api', '0004_alter_leetcodeproblemsmodel_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcodeproblemsmodel',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'EASY'), ('Medium', 'MEDIUM'), ('Hard', 'HARD')], max_length=15, null=True),
        ),
    ]
