# Generated by Django 5.1.1 on 2024-09-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc_api', '0005_alter_leetcodeproblemsmodel_difficulty'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contestmodel',
            table='contest',
        ),
        migrations.AlterModelTable(
            name='leetcodeproblemsmodel',
            table='problems',
        ),
    ]
