# Generated by Django 5.1.1 on 2024-09-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_api', '0006_alter_contestmodel_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='leetcodeproblemsmodel',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='leetcodeproblemsmodel',
            name='tags',
            field=models.ManyToManyField(related_name='leetcode_problems', to='lc_api.tagmodel'),
        ),
    ]
